import NavBar from "@/components/navbar/NavBar.jsx";
import Footer from "@/components/footer/Footer.jsx";
import "./globals.css";
import { ThemeCOntextProvider } from "@/context/themeContextToggle.js";
import AuthProvider from "@/components/AuthProvider/AuthProvider.jsx";


export const metadata = {
  title: "ALi | Missoum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body >
        <ThemeCOntextProvider>
          <AuthProvider>
          <div className="container">
            <NavBar />
            {children}
            <Footer />
          </div>
          </AuthProvider>
        </ThemeCOntextProvider>
      </body>
    </html>
  );
}
